# Site settings
name: "minho choi"
email: "minho2002"
url: "https://minho2002/minho2002.github.io"
description: "My blog"
author: "minho choi"
title: "Mino's Blog"
permalink: pretty
baseurl: ""

# social
github:
  username: minho2002

twitter:
  username: username
