# Site settings
name: "minho choi"
email: "minho_2002@naver.com"
url: url
description: "mino's blog"
author: "minho choi"
title: "minho's blog"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: minho2002

twitter:
  username: username
